### ISSUE TITLE
Change API Calls?

### ISSUE THREAD

**Issue by owensiemons** [CS196Illinois/Group6-FA23#38]

**Comment by drew-oberweis** [comment]
Interesting bit of info Chen found - this does actually seem to be due to a stock split, and Alpaca just handles it in a somewhat stupid way. See attached photo.

![Image](https://github.com/CS196Illinois/Group6-FA23/assets/58198203/b7e50de1-eff9-408b-aadd-43a6777972f3)

**Comment by drew-oberweis** [comment]
Fixed a while ago
